### PR TITLE
Add 'new' command to generate a misaki project

### PR DESCRIPTION
**Pull request by liquidz**
I added 'new' command to generate a misaki project from lein-misaki.

``` sh
# Generate project with default template
lein misaki new PROJECT_NAME

# Generate project with specified template
lein misaki new PROJECT_NAME TEMPLATE_NAME
```

Template files are managed at [misaki-showcase](https://github.com/liquidz/misaki-showcase) repository.

### CODE REVIEW

**Comment by skuro** [comment]
I see your point. I still think supporting `lein-newnew` might be a nice to have, since a lot of people already use it and might be confused by this alternative version of templates management.

Still, it's already decided how Misaki will behave, and `lein-misaki` needs to at least support it. I think a `lein-newnew` approach can just be done separately, if needed.

BTW: your English is definitely good enough, and trust me, it's suer-duper awesome compared to my Japanese :-)

**Comment by liquidz** [comment]
@skuro I missed following explanation of lein-newnew..

https://github.com/Raynes/lein-newnew#distributing-your-template

> In Leiningen 2.x, templates get dynamically fetched if they're not found. So for instance lein new heroku myproject will find the latest version of the heroku/lein-template project from Clojars and use that.

This function solves my all concerns.
So, as you say, lein-newnew approach is the best, and this pull-request may be unnecessary...

**Comment by skuro** [comment]
I'm going to leave it as it is right now, and experiment with using a proper `lein-newnew` approach. As soon as I have a working and documented process we'll revert this commit.

**Comment by liquidz** [comment]
I made a default misaki template(alpha ver) with lein-newnew for experiment.
https://github.com/liquidz/misaki-templates/tree/master/misaki-default-template

**Pull request merged**
